version: '3.2'

services:
  discovery:
    build: discovery/
    networks:
      - microservice
    ports:
      - "8081:8081"

  gateway:
    build: gateway/
    networks:
      - microservice
    environment:
      - EUREKA_SERVER_HOSTNAME=discovery
      - EUREKA_SERVER_PORT=8081
    ports:
      - "8080:8080"

  course:
    build: course/
    networks:
      - microservice
    environment:
      - EUREKA_SERVER_HOSTNAME=discovery
      - EUREKA_SERVER_PORT=8081

networks:
  microservice:
    external: true
